kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node
spec:
  template:
    spec:
      containers:
        - name: csi-driver-registrar
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/pd.dev.csi.storage.gke.io/csi.sock"
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/pd.dev.csi.storage.gke.io/
            type: DirectoryOrCreate
