apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-gce-pd-with-resource-tags
provisioner: pd.csi.storage.gke.io
parameters:
  resource-tags: <parent_id1>/<tag_key1>/<tag_value1>,<parent_id2>/<tag_key2>/<tag_value2>
volumeBindingMode: WaitForFirstConsumer